baseurl = "http://www.botscripter.io"
title = "botscripter"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
  author = "Nikola StankoviÄ‡"
  info = "Software Engineer"
  description = "botscripter's blog"
  keywords = "productionreadiness,opensource,agile,scrum,kanban,java,go,kotlin,python,cloud,cloudnative,devops,devsecops,code,blog,developer,programmer,personal,software,architecture,sql,nosql,kubernetes,openshift"
  avatarurl = "images/avatar.jpg"

  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  footercontent = "#ProductionReadiness #SpringBoot #OpenSource #Agile #CloudNative #DevSecOps #SoftwareArchitecture #Java #Kotlin #Python #Go #BPM #Kubernetes #SQL #NoSQL"
  hideFooter = false
  hideCredits = true
  hideCopyright = false
  since = 2021

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/botscripter/"
[[params.social]]
  name = "Linkedin"
  icon = "fa fa-linkedin fa-2x"
  weight = 2
  url = "https://www.linkedin.com/in/stankovic-nikola/"
[[params.social]]
  name = "Twitter"
  icon = "fa fa-twitter fa-2x"
  weight = 3
  url = "https://twitter.com/botscripter/"
[[params.social]]
  name = "Medium"
  icon = "fa fa-medium fa-2x"
  weight = 4
  url = "https://medium.com/@botscripter"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"
